// Textos de la interfaz en español (es el idioma original de la app). Las claves
// son las mismas en en.js. {nombre} marca un hueco que se rellena al usar el
// texto: t('clave', { nombre: 'Zelda' }).
export default {
  // ---- Comunes ----
  'comun.cerrar': 'Cerrar',
  'comun.cancelar': 'Cancelar',
  'comun.guardando': 'Guardando...',
  'comun.sinPortada': 'Sin portada',
  'comun.buscarJuegos': 'Buscar juegos',

  // ---- Errores que genera el cliente (los del backend se traducen en en.js) ----
  'api.sinConexion': 'No se pudo conectar con el servidor',
  'api.errorInesperado': 'Error inesperado del servidor',

  // ---- Validaciones de formularios ----
  'validacion.emailInvalido': 'El email no tiene un formato válido',
  'validacion.passwordRequisitos': 'La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula y un número',
  'validacion.usernameObligatorio': 'El nombre de usuario es obligatorio',

  // ---- Estados de un juego ----
  'estado.jugando': 'Jugando',
  'estado.completado': 'Completado',
  'estado.abandonado': 'Abandonado',
  'estado.pendiente': 'Pendiente',

  // ---- Marca y barra superior ----
  'marca.irBiblioteca': 'GameHub, ir a Mi biblioteca',
  'menu.biblioteca': 'Mi biblioteca',
  'menu.buscar': 'Buscar',
  'menu.usuario': 'Menú de usuario',
  'menu.verPerfil': 'Ver perfil',
  'menu.cerrarSesion': 'Cerrar sesión',
  'ajustes.menu': 'Ajustes',
  'ajustes.idioma': 'Idioma',
  'ajustes.tema': 'Tema',
  'ajustes.temaClaro': 'Tema claro',
  'ajustes.temaOscuro': 'Tema oscuro',

  // ---- Inicio de sesión y registro ----
  'auth.email': 'Email',
  'auth.password': 'Contraseña',
  'auth.login.titulo': 'Iniciar sesión',
  'auth.login.passwordVacia': 'Introduce tu contraseña',
  'auth.login.entrando': 'Entrando...',
  'auth.login.sinCuenta': '¿No tienes cuenta?',
  'auth.login.registrate': 'Regístrate',
  'auth.registro.titulo': 'Crear cuenta',
  'auth.registro.username': 'Nombre de usuario',
  'auth.registro.passwordAyuda': 'Mínimo 8 caracteres, con mayúscula, minúscula y número.',
  'auth.registro.registrando': 'Registrando...',
  'auth.registro.boton': 'Registrarse',
  'auth.registro.yaCuenta': '¿Ya tienes cuenta?',
  'auth.registro.iniciaSesion': 'Inicia sesión',

  // ---- Mi biblioteca ----
  'biblioteca.cargando': 'Cargando tu biblioteca...',
  'biblioteca.vaciaTitulo': 'Tu biblioteca está vacía',
  'biblioteca.vaciaTexto': 'Aún no has guardado ningún juego.',
  'biblioteca.titulo': 'Mi biblioteca',
  'biblioteca.filtrarPorEstado': 'Filtrar por estado',
  'biblioteca.estado': 'Estado',
  'biblioteca.todos': 'Todos',
  'biblioteca.filtrarJuegos': 'Filtrar mis juegos',
  'biblioteca.sinResultadosTitulo': 'Ningún juego coincide',
  'biblioteca.sinResultadosAntes': 'Prueba con otro filtro o ',
  'biblioteca.sinResultadosEnlace': 'busca juegos nuevos',
  'biblioteca.sinResultadosDespues': ' para añadirlos.',
  'jugando.titulo': 'Jugando ahora',

  // ---- Tarjetas y edición de un juego ----
  'juego.estadoDe': 'Estado de {nombre}',
  'juego.tieneResena': 'Tiene reseña',
  'juego.editar': 'Editar',
  'juego.quitar': 'Quitar',
  'juego.quitarTitulo': 'Quitar juego',
  'juego.quitarMensaje': '¿Quitar "{nombre}" de tu biblioteca? Se perderán su estado, nota y reseña.',
  'editar.etiqueta': 'Editar juego',
  'editar.estado': 'Estado',
  'editar.nota': 'Nota (1-10)',
  'editar.plataforma': 'Plataforma',
  'editar.resena': 'Reseña',
  'editar.cargando': 'Cargando...',
  'editar.sinEspecificar': 'Sin especificar',
  'editar.errorPlataformas': 'No se pudo cargar la lista de plataformas.',
  'editar.guardar': 'Guardar',
  'anadir.guardando': 'Guardando...',
  'anadir.anadido': '✓ En tu biblioteca',
  'anadir.boton': 'Añadir a mi biblioteca',

  // ---- Buscar ----
  'buscar.titulo': 'Añade tu juego a la biblioteca',
  'buscar.texto': 'Busca en el catálogo de IGDB y guarda lo que quieras jugar en tu biblioteca.',
  'buscar.placeholder': 'Busca un juego...',
  'buscar.etiqueta': 'Buscar un juego',
  'buscar.vacio': 'Escribe el nombre de un juego para buscarlo en IGDB.',
  'buscar.buscando': 'Buscando...',
  'buscar.resultadosPara': 'Resultados para “{termino}”',
  'buscar.marcados': 'Los que ya tienes aparecen marcados',

  // ---- Ficha de un juego ----
  'detalle.cargando': 'Cargando información...',
  'detalle.valoraciones': '{n} valoraciones',
  'detalle.lanzamiento': 'Lanzamiento',
  'detalle.desarrolladora': 'Desarrolladora',
  'detalle.publisher': 'Publisher',
  'detalle.generos': 'Géneros',
  'detalle.modos': 'Modos de juego',
  'detalle.plataformas': 'Plataformas',
  'detalle.enBiblioteca': 'En tu biblioteca',
  'detalle.sinResena': 'Todavía no has escrito ninguna reseña.',
  'detalle.descripcion': 'Descripción',
  'detalle.descripcionTraducida': 'Traducida automáticamente del inglés. Descripción original de IGDB.',
  'detalle.descripcionOriginal': 'Descripción original de IGDB, en inglés.',
  'detalle.capturas': 'Capturas',
  'detalle.ampliarCaptura': 'Ampliar captura {n}',
  'detalle.verIgdb': 'Ver en IGDB',
  'visor.captura': 'Captura {n} de {total}',
  'visor.anterior': 'Captura anterior',
  'visor.siguiente': 'Captura siguiente',

  // ---- Perfil ----
  'perfil.cargando': 'Cargando tu perfil...',
  'perfil.miembroDesde': 'Miembro desde {fecha}',
  'perfil.sinBio': 'Aún no has escrito nada sobre ti.',
  'perfil.estadisticas': 'Estadísticas',
  'perfil.calculando': 'Calculando estadísticas...',
  'perfil.editar': 'Editar perfil',
  'perfil.cuenta': 'Cuenta',

  'stats.vacio': 'Todavía no has guardado ningún juego, así que no hay nada que contar.',
  'stats.juegos': 'Juegos',
  'stats.notaMedia': 'Nota media',
  'stats.valorados': ' · {n} valorados',
  'stats.completados': 'Completados',
  'stats.porEstado': 'Por estado',
  'stats.mejores': 'Mejor valorados',

  'editarPerfil.noImagen': 'El archivo elegido no es una imagen',
  'editarPerfil.subir': 'Subir foto',
  'editarPerfil.elegirIlustracion': 'Elegir ilustración de mis juegos',
  'editarPerfil.quitarFoto': 'Quitar foto',
  'editarPerfil.ayudaFoto': 'Sube un JPG, PNG o WebP o usa una ilustración de uno de tus juegos. Después eliges el encuadre.',
  'editarPerfil.buscandoIlustraciones': 'Buscando ilustraciones de tus juegos...',
  'editarPerfil.sinIlustraciones': 'Ninguno de tus juegos tiene ilustraciones en IGDB todavía. Añade más desde Buscar.',
  'editarPerfil.username': 'Nombre de usuario',
  'editarPerfil.bio': 'Sobre mí',
  'editarPerfil.bioPlaceholder': 'Qué te gusta jugar, tu género favorito...',
  'editarPerfil.actualizado': 'Perfil actualizado',
  'editarPerfil.guardar': 'Guardar cambios',
  'artwork.ilustracion': 'Ilustración {n} de {nombre}',

  'recortador.volver': 'Volver',
  'recortador.errorPreparar': 'No se pudo preparar la imagen. Prueba con otra',
  'recortador.errorCargar': 'No se pudo cargar la imagen. Prueba con otra',
  'recortador.encuadre': 'Encuadre de la foto. Arrastra para mover, usa la rueda o las teclas más y menos para ampliar o reducir.',
  'recortador.zoom': 'Zoom',
  'recortador.reducir': 'Reducir',
  'recortador.ampliar': 'Ampliar',
  'recortador.ayuda': 'Arrastra la imagen para moverla. Amplía y reduce con la rueda, el deslizador o pellizcando.',
  'recortador.restablecer': 'Restablecer',
  'recortador.usar': 'Usar como foto',

  // ---- Ajustes de la cuenta ----
  'cuenta.emailTitulo': 'Email',
  'cuenta.email': 'Email',
  'cuenta.passwordActual': 'Contraseña actual',
  'cuenta.emailActualizado': 'Email actualizado',
  'cuenta.cambiarEmail': 'Cambiar email',
  'cuenta.passwordTitulo': 'Contraseña',
  'cuenta.passwordNuevaRequisitos': 'La nueva contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula y un número',
  'cuenta.passwordNoCoinciden': 'Las contraseñas nuevas no coinciden',
  'cuenta.passwordNueva': 'Nueva contraseña',
  'cuenta.passwordRepite': 'Repite la nueva contraseña',
  'cuenta.passwordActualizada': 'Contraseña actualizada',
  'cuenta.cambiarPassword': 'Cambiar contraseña',
  'cuenta.borrarTitulo': 'Borrar cuenta',
  'cuenta.borrarAviso': 'Se eliminarán tu cuenta y toda tu biblioteca. No se puede deshacer.',
  'cuenta.borrando': 'Borrando...',
  'cuenta.borrarBoton': 'Borrar mi cuenta',
  'cuenta.borrarConfirmarTitulo': '¿Borrar tu cuenta?',
  'cuenta.borrarConfirmarMensaje': 'Perderás tu perfil y todos los juegos de tu biblioteca. Esta acción no se puede deshacer.',
  'cuenta.borrarConfirmar': 'Borrar para siempre',
}
